import js from '@eslint/js'
import globals from 'globals'
import reactHooks from 'eslint-plugin-react-hooks'
import reactRefresh from 'eslint-plugin-react-refresh'
import tseslint from 'typescript-eslint'
import { defineConfig, globalIgnores } from 'eslint/config'

const LEGACY_FILES = [
  'src/components/ai/ChatItems.tsx',
  'src/components/ai/ClarificationRequestCard.tsx',
  'src/components/ai/OracleCard.tsx',
  'src/components/biometrics/DailyStrainCard.tsx',
  'src/components/biometrics/MuscleHeatmap.tsx',
  'src/components/biometrics/SaunaLoggerModal.tsx',
  'src/components/biometrics/WorkoutLogger.tsx',
  'src/components/biometrics/workout/ExerciseCard.tsx',
  'src/components/calendar/CalendarView.tsx',
  'src/components/cards/CardFactory.tsx',
  'src/components/core/DailyShutdownModal.tsx',
  'src/components/core/DailySnapshotCard.tsx',
  'src/components/core/Dashboard.tsx',
  'src/components/core/DashboardModals.tsx',
  'src/components/core/Fundament.tsx',
  'src/components/core/MorningPlanModal.tsx',
  'src/components/core/NutritionCard.tsx',
  'src/components/core/NutritionChart.tsx',
  'src/components/core/Stats.tsx',
  'src/components/core/nutrition/FoodEntryModal.tsx',
  'src/components/core/nutrition/FoodQuickCapture.tsx',
  'src/components/core/nutrition/NutritionTrainingBar.tsx',
  'src/components/core/nutrition/useFoodEntryData.ts',
  'src/components/core/stats/FoodAnalysisSection.tsx',
  'src/components/core/stats/TrainingAnalysisSection.tsx',
  'src/components/core/stats/WorkoutHistorySection.tsx',
  'src/components/core/stats/exportStats.ts',
  'src/components/core/useNutritionData.ts',
  'src/components/correlations/CorrelationsPage.tsx',
  'src/components/desktop/DesktopDashboard.tsx',
  'src/components/desktop/DreamEditModal.tsx',
  'src/components/desktop/DreamsPanel.tsx',
  'src/components/desktop/FitnessScorePanel.tsx',
  'src/components/desktop/GeneralView.tsx',
  'src/components/desktop/HabitsPanel.tsx',
  'src/components/desktop/Heatmap.tsx',
  'src/components/desktop/HexagonPanel.tsx',
  'src/components/desktop/IntelligencePanel.tsx',
  'src/components/desktop/MarathonPanel.tsx',
  'src/components/desktop/SprintPanel.tsx',
  'src/components/desktop/SupplementsPanel.tsx',
  'src/components/desktop/VisionBoardPanel.tsx',
  'src/components/desktop/desktopUtils.ts',
  'src/components/desktop/useDesktopData.ts',
  'src/components/desktop/useDreamsData.ts',
  'src/components/growth/GrowthCockpit.tsx',
  'src/components/growth/GrowthLearningPanel.tsx',
  'src/components/growth/GrowthSkillsList.tsx',
  'src/components/growth/GrowthView.tsx',
  'src/components/growth/GrowthWeekPlan.tsx',
  'src/components/growth/PinPickerModal.tsx',
  'src/components/growth/SkillRadarPanel.tsx',
  'src/components/identity/IdentityVault.tsx',
  'src/components/identity/Photos.tsx',
  'src/components/integrations/StravaWidget.tsx',
  'src/components/lifestyle/Direction.tsx',
  'src/components/lifestyle/DirectionPlanningMode.tsx',
  'src/components/lifestyle/DirectionRadarMode.tsx',
  'src/components/lifestyle/DirectionSprintMode.tsx',
  'src/components/lifestyle/LinksInbox.tsx',
  'src/components/lifestyle/PowerList.tsx',
  'src/components/lifestyle/PowerListKpi.tsx',
  'src/components/lifestyle/PowerListTask.tsx',
  'src/components/lifestyle/ProjectWeekKpis.tsx',
  'src/components/lifestyle/WeekHub.tsx',
  'src/components/lifestyle/WeeklyBalanceHexagon.tsx',
  'src/components/lifestyle/directionHelpers.ts',
  'src/components/lifestyle/usePowerListData.ts',
  'src/components/medical/EndMyopiaCalculator.tsx',
  'src/components/medical/MedicalStudiesPage.tsx',
  'src/components/notes/EditNoteModal.tsx',
  'src/components/notes/Keep.tsx',
  'src/components/notes/NoteCard.tsx',
  'src/components/notes/NoteQuickCapture.tsx',
  'src/components/notes/RichEditor.tsx',
  'src/components/projects/GoalCreateModal.tsx',
  'src/components/projects/LifeGoalsCard.tsx',
  'src/components/projects/ProjectCard.tsx',
  'src/components/projects/Projects.tsx',
  'src/components/projects/RetroModal.tsx',
  'src/components/projects/projectUtils.ts',
  'src/components/todo/ContextMenu.tsx',
  'src/components/todo/DragGhost.tsx',
  'src/components/todo/EisenhowerMatrix.tsx',
  'src/components/todo/KanbanView.tsx',
  'src/components/todo/Todo.tsx',
  'src/components/todo/TodoCard.tsx',
  'src/components/todo/TodoDatePickerPopover.tsx',
  'src/components/todo/TodoQuickCapture.tsx',
  'src/components/todo/TodoScanTextModal.tsx',
  'src/components/todo/TodoSidebar.tsx',
  'src/components/todo/WeeklyReviewModal.tsx',
  'src/components/todo/useTodoData.ts',
  'src/data/exercises.ts',
  'src/hooks/useCalendarTodos.ts',
  'src/hooks/useDirection.ts',
  'src/hooks/useDirectionContext.ts',
  'src/hooks/useGrowthData.ts',
  'src/hooks/useSyncActivities.ts',
  'src/lib/aiContext.ts',
  'src/lib/dailyPlanProposal.ts',
  'src/lib/database.types.ts',
  'src/lib/fitnessScore.ts',
  'src/lib/foodLogging.ts',
  'src/lib/goalLineage.ts',
  'src/lib/goalSpine.mutations.ts',
  'src/lib/goalSpine.queries.ts',
  'src/lib/lifeGoals.ts',
  'src/lib/offlineQueue.ts',
  'src/lib/supabaseUtils.ts',
  'src/lib/supplementsClient.ts',
  'src/lib/todoParser.ts',
  'src/lib/workoutLogging.test.ts',
  'src/lib/workoutLogging.ts',
]

export default defineConfig([
  globalIgnores(['dist', '.tmp-get-based']),
  {
    files: ['scripts/**/*.{js,cjs,mjs}'],
    extends: [
      js.configs.recommended,
    ],
    languageOptions: {
      globals: { ...globals.node, ...globals.browser },
    },
    rules: {
      'no-unused-vars': ['error', { varsIgnorePattern: '^_', argsIgnorePattern: '^_', caughtErrorsIgnorePattern: '^_' }],
    },
  },
  {
    files: ['src/**/*.{js,jsx,ts,tsx}'],
    ignores: ['scripts/**', ...LEGACY_FILES],
    extends: [
      js.configs.recommended,
      ...tseslint.configs.recommended,
      reactHooks.configs.flat.recommended,
      reactRefresh.configs.vite,
    ],
    languageOptions: {
      globals: globals.browser,
      parserOptions: { ecmaFeatures: { jsx: true } },
    },
    rules: {
      // base rule off — TS version below handles it with better type-awareness
      'no-unused-vars': 'off',
      // warn (not error) so --max-warnings threshold controls CI gate
      '@typescript-eslint/no-unused-vars': ['warn', {
        varsIgnorePattern: '^_',
        argsIgnorePattern: '^_',
        caughtErrorsIgnorePattern: '^_',
      }],
      '@typescript-eslint/no-explicit-any': 'error',
      'max-lines': ['error', { max: 300, skipBlankLines: true, skipComments: true }],
      'max-lines-per-function': ['error', { max: 150, skipBlankLines: true, skipComments: true }],
      // allow ts-ignore only when it carries a reason comment
      '@typescript-eslint/ban-ts-comment': ['warn', { 'ts-ignore': 'allow-with-description' }],
      // empty catch blocks are intentional (localStorage fallbacks etc.)
      'no-empty': ['warn', { allowEmptyCatch: true }],
      'no-restricted-syntax': 'off',
    }
  },
  {
    // Legacy exceptions list (can only decrease in size over time)
    files: LEGACY_FILES,
    extends: [
      js.configs.recommended,
      ...tseslint.configs.recommended,
      reactHooks.configs.flat.recommended,
      reactRefresh.configs.vite,
    ],
    languageOptions: {
      globals: globals.browser,
      parserOptions: { ecmaFeatures: { jsx: true } },
    },
    rules: {
      'no-unused-vars': 'off',
      '@typescript-eslint/no-unused-vars': ['warn', {
        varsIgnorePattern: '^_',
        argsIgnorePattern: '^_',
        caughtErrorsIgnorePattern: '^_',
      }],
      '@typescript-eslint/no-explicit-any': 'warn',
      'max-lines': 'off',
      'max-lines-per-function': 'off',
      '@typescript-eslint/ban-ts-comment': ['warn', { 'ts-ignore': 'allow-with-description' }],
      'no-empty': ['warn', { allowEmptyCatch: true }],
      'no-restricted-syntax': 'off',
    }
  }
])
