export type CorrelationCategory = 'sen' | 'zywienie' | 'trening' | 'regeneracja' | 'zachowanie' | 'suplementy' | 'ekran'

/** Human labels for known metrics; behavior_log keys get labels at runtime. */
export const METRIC_LABELS: Record<string, string> = {
  sleep_h: 'Długość snu (h)',
  sleep_score: 'Sleep score',
  sleep_efficiency: 'Efektywność snu',
  sleep_latency: 'Latency snu (min)',
  deep_sleep_h: 'Sen głęboki (h)',
  rem_sleep_h: 'Sen REM (h)',
  light_sleep_h: 'Sen lekki (h)',
  sleep_hr: 'HR w trakcie snu',
  sleep_hrv: 'HRV w trakcie snu',
  sleep_lowest_hr: 'Min HR w śnie',
  restless_periods: 'Niespokojne okresy',
  temp_deviation: 'Odchylenie temp.',
  spo2: 'SpO2',
  vo2max: 'VO2max',
  stress_high_min: 'Minuty wysokiego stresu',
  met_avg: 'MET (średnio)',
  sedentary_min: 'Siedzenie (min)',
  bedtime_hour: 'Godzina pójścia spać',
  hrv: 'HRV',
  rhr: 'RHR',
  readiness: 'Readiness',
  strain: 'Strain',
  recovery: 'Recovery',
  cns_load: 'CNS load',
  leg_load: 'Leg load',
  mental_load: 'Mental load',
  illness_score: 'Illness score',
  fueling: 'Fueling score',
  calories: 'Kalorie',
  protein: 'Białko',
  carbs: 'Węglowodany',
  fat: 'Tłuszcz',
  sugar: 'Cukier',
  fiber: 'Błonnik',
  insulin_load: 'Insulin load',
  food_quality: 'Jakość jedzenia',
  steps: 'Kroki',
  caffeine_mg: 'Kofeina (mg)',
  caffeine_late_mg: 'Późna kofeina (mg)',
  last_coffee_hour: 'Godzina ostatniej kawy',
  last_meal_hour: 'Godzina ostatniego posiłku',
  calories_late: 'Kalorie po 20:00',
  workout_hr_peak: 'Peak HR treningu',
  workout_hr_avg: 'Średnie HR treningu',
  workout_strain: 'HR strain treningu',
  run_hr: 'HR biegu (Strava)',
  run_rpe: 'RPE biegu',
  run_cadence: 'Kadencja biegu',
  run_suffer: 'Suffer score biegu',
  run_distance_km: 'Dystans biegu (km)',
  cardio: 'Cardio load',
  strength: 'Siłownia load',
  mood_score: 'Nastrój (1–10)',
  daily_rpe: 'RPE dnia',
  plan_done_pct: 'Wykonanie planu (%)',
  day_score: 'Ocena dnia (reconciliation)',
  phone_drift: 'Scroll rano',
  execution_score: 'Execution score',
  identity_score: 'Identity score',
  dopamine_load_index: 'Dopamine load',
  screen_time_min: 'Czas ekranu (min)',
  fragmentation_index: 'Fragmentacja dnia',
  productivity_ratio: 'Produktywność ekranu',
  phone_active_h: 'Telefon aktywny (h)',
  friction_count: 'Liczba tarć',
  avoidance_count: 'Unikanie',
  procrastination_count: 'Prokrastynacja',
  alcohol_units: 'Alkohol (jednostki)',
  travel_day: 'Dzień podróży',
  illness_day: 'Choroba (severity)',
  stress_manual: 'Stres (manual)',
  creatine_taken: 'Kreatyna',
  omega3_taken: 'Omega-3',
  lions_mane_taken: "Lion's mane",
  d3_taken: 'D3+K2',
  habit_count: 'Nawyki zaliczone',
  weight_kg: 'Waga (kg)',
}
